-- ==============================================================================
-- ADD TEAM MAP STATS & TELEMETRY TABLE TO SUPABASE DATABASE
-- (Copy and run this in Supabase -> SQL Editor)
-- ==============================================================================

-- 1. Create Team Map Records Table
CREATE TABLE IF NOT EXISTS team_map_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT REFERENCES teams(id) ON DELETE CASCADE,
    map_name TEXT NOT NULL,       -- e.g. "Karachi", "Sub Base", "Rio", "Highrise", "6 Star", "Terminal", "Invasion"
    game_mode TEXT NOT NULL,      -- e.g. "Hardpoint", "Search & Destroy", "Control"
    wins INT DEFAULT 0,
    losses INT DEFAULT 0,
    win_rate INT DEFAULT 0,
    streak TEXT DEFAULT '1W',
    recent_score TEXT,            -- e.g. '250 - 210 vs Vantage'
    recent_result TEXT DEFAULT 'W',-- 'W' or 'L'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE team_map_records ENABLE ROW LEVEL SECURITY;

-- 3. Allow Public Read Access
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'team_map_records' 
        AND policyname = 'Allow public read access on team_map_records'
    ) THEN
        CREATE POLICY "Allow public read access on team_map_records" ON team_map_records
            FOR SELECT USING (true);
    END IF;
END
$$;

-- 4. Sample Team Map Records (Clean initial state — real map stats are computed dynamically from official match results)
-- Records are populated automatically when matches are reported.

