-- ==============================================================================
-- ADD PLAYER MAP STATS TABLE TO YOUR EXISTING SUPABASE DATABASE
-- (Copy and run this in Supabase -> SQL Editor)
-- ==============================================================================

-- 1. Create Individual Player Map Stats Table
CREATE TABLE IF NOT EXISTS player_map_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT REFERENCES players(id) ON DELETE CASCADE,
    map_name TEXT NOT NULL,       -- e.g. "Sub Base", "Karachi", "Invasion", "Rio", "Highrise", "6 Star", "Terminal"
    game_mode TEXT NOT NULL,      -- e.g. "Hardpoint", "Search & Destroy", "Control"
    opponent_team TEXT,           -- e.g. "Vantage", "Redline", "Static", "Night Shift"
    kills INT DEFAULT 0,
    deaths INT DEFAULT 0,
    damage INT DEFAULT 0,
    kdr NUMERIC(4, 2) DEFAULT 1.00,
    result TEXT DEFAULT 'W',      -- 'W' or 'L'
    score TEXT,                   -- e.g. '250 - 212', '6 - 4', '3 - 2'
    match_date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE player_map_stats ENABLE ROW LEVEL SECURITY;

-- 3. Allow Public Read Access
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'player_map_stats' 
        AND policyname = 'Allow public read access on player_map_stats'
    ) THEN
        CREATE POLICY "Allow public read access on player_map_stats" ON player_map_stats
            FOR SELECT USING (true);
    END IF;
END
$$;

-- 4. Insert Sample Match Map Records
INSERT INTO player_map_stats (player_id, map_name, game_mode, opponent_team, kills, deaths, damage, kdr, result, score, match_date) VALUES
-- Apex (Night Shift)
((SELECT id FROM players WHERE gamertag = 'Apex'), 'Karachi', 'Hardpoint', 'Vantage', 32, 21, 4820, 1.52, 'W', '250 - 210', '2026-09-24'),
((SELECT id FROM players WHERE gamertag = 'Apex'), 'Highrise', 'Search & Destroy', 'Vantage', 9, 5, 1450, 1.80, 'W', '6 - 4', '2026-09-24'),
((SELECT id FROM players WHERE gamertag = 'Apex'), 'Invasion', 'Control', 'Vantage', 24, 19, 3610, 1.26, 'L', '2 - 3', '2026-09-24'),
((SELECT id FROM players WHERE gamertag = 'Apex'), 'Sub Base', 'Hardpoint', 'Redline', 29, 22, 4390, 1.32, 'W', '250 - 195', '2026-09-18'),
((SELECT id FROM players WHERE gamertag = 'Apex'), 'Rio', 'Search & Destroy', 'Redline', 11, 4, 1820, 2.75, 'W', '6 - 2', '2026-09-18'),

-- Ghost (Night Shift)
((SELECT id FROM players WHERE gamertag = 'Ghost'), 'Karachi', 'Hardpoint', 'Vantage', 26, 18, 4410, 1.44, 'W', '250 - 210', '2026-09-24'),
((SELECT id FROM players WHERE gamertag = 'Ghost'), 'Highrise', 'Search & Destroy', 'Vantage', 7, 6, 1200, 1.17, 'W', '6 - 4', '2026-09-24'),
((SELECT id FROM players WHERE gamertag = 'Ghost'), 'Invasion', 'Control', 'Vantage', 21, 20, 3450, 1.05, 'L', '2 - 3', '2026-09-24'),
((SELECT id FROM players WHERE gamertag = 'Ghost'), 'Sub Base', 'Hardpoint', 'Redline', 27, 19, 4100, 1.42, 'W', '250 - 195', '2026-09-18'),

-- Specter (Vantage)
((SELECT id FROM players WHERE gamertag = 'Specter'), 'Karachi', 'Hardpoint', 'Night Shift', 29, 24, 4650, 1.21, 'L', '210 - 250', '2026-09-24'),
((SELECT id FROM players WHERE gamertag = 'Specter'), 'Highrise', 'Search & Destroy', 'Night Shift', 8, 7, 1310, 1.14, 'L', '4 - 6', '2026-09-24'),
((SELECT id FROM players WHERE gamertag = 'Specter'), 'Invasion', 'Control', 'Night Shift', 27, 18, 4120, 1.50, 'W', '3 - 2', '2026-09-24'),
((SELECT id FROM players WHERE gamertag = 'Specter'), '6 Star', 'Hardpoint', 'Static', 34, 21, 5100, 1.62, 'W', '250 - 180', '2026-09-17'),

-- Reaper (Redline)
((SELECT id FROM players WHERE gamertag = 'Reaper'), 'Sub Base', 'Hardpoint', 'Night Shift', 26, 25, 4120, 1.04, 'L', '195 - 250', '2026-09-18'),
((SELECT id FROM players WHERE gamertag = 'Reaper'), 'Rio', 'Search & Destroy', 'Night Shift', 6, 7, 980, 0.86, 'L', '2 - 6', '2026-09-18'),
((SELECT id FROM players WHERE gamertag = 'Reaper'), 'Karachi', 'Hardpoint', 'Static', 31, 20, 4750, 1.55, 'W', '250 - 220', '2026-09-11'),

-- Titan (Static)
((SELECT id FROM players WHERE gamertag = 'Titan'), '6 Star', 'Hardpoint', 'Vantage', 24, 26, 3890, 0.92, 'L', '180 - 250', '2026-09-17'),
((SELECT id FROM players WHERE gamertag = 'Titan'), 'Karachi', 'Hardpoint', 'Redline', 25, 23, 3950, 1.09, 'L', '220 - 250', '2026-09-11');
