-- ==============================================================================
-- FRONTLINE CALL OF DUTY LEAGUE - 8-WEEK MATCH SCHEDULE SCHEMA
-- (Copy and run this in your Supabase Dashboard -> SQL Editor to enable cloud schedule)
-- ==============================================================================

-- 1. Create scheduled_matches table
CREATE TABLE IF NOT EXISTS scheduled_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_number INT NOT NULL,                        -- 1 through 8
    season_type TEXT NOT NULL DEFAULT 'regular',     -- 'preseason' (Weeks 1-2) or 'regular' (Weeks 3-8)
    week_label TEXT NOT NULL,                        -- 'Preseason Week 1', 'Regular Season Week 1', etc.
    match_number INT DEFAULT 1,                      -- Sequential match number in season
    
    -- Team 1
    team1_id BIGINT REFERENCES teams(id) ON DELETE SET NULL,
    team1_name TEXT NOT NULL,
    team1_tag TEXT NOT NULL,
    team1_score INT DEFAULT 0,
    
    -- Team 2
    team2_id BIGINT REFERENCES teams(id) ON DELETE SET NULL,
    team2_name TEXT NOT NULL,
    team2_tag TEXT NOT NULL,
    team2_score INT DEFAULT 0,
    
    -- Result & Scheduling details
    winner_id BIGINT REFERENCES teams(id) ON DELETE SET NULL,
    winner_name TEXT,
    status TEXT DEFAULT 'Scheduled',                 -- 'Scheduled', 'Live', 'Completed'
    scheduled_date DATE DEFAULT CURRENT_DATE,
    scheduled_time TEXT DEFAULT '7:00 PM EST',
    best_of INT DEFAULT 5,                           -- Best of 5 standard (or 3)
    stream_url TEXT,                                 -- Twitch channel / VOD URL / embed link
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Indexes for fast query filtering
CREATE INDEX IF NOT EXISTS idx_scheduled_matches_week ON scheduled_matches(week_number);
CREATE INDEX IF NOT EXISTS idx_scheduled_matches_season_type ON scheduled_matches(season_type);
CREATE INDEX IF NOT EXISTS idx_scheduled_matches_status ON scheduled_matches(status);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE scheduled_matches ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies (Read allowed for public, full mutations for admin / anon key)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'scheduled_matches' AND policyname = 'Allow public read access on scheduled_matches'
    ) THEN
        CREATE POLICY "Allow public read access on scheduled_matches" 
        ON scheduled_matches FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'scheduled_matches' AND policyname = 'Allow insert on scheduled_matches'
    ) THEN
        CREATE POLICY "Allow insert on scheduled_matches" 
        ON scheduled_matches FOR INSERT WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'scheduled_matches' AND policyname = 'Allow update on scheduled_matches'
    ) THEN
        CREATE POLICY "Allow update on scheduled_matches" 
        ON scheduled_matches FOR UPDATE USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'scheduled_matches' AND policyname = 'Allow delete on scheduled_matches'
    ) THEN
        CREATE POLICY "Allow delete on scheduled_matches" 
        ON scheduled_matches FOR DELETE USING (true);
    END IF;
END $$;
