-- ==============================================================================
-- FRONTLINE CALL OF DUTY LEAGUE - PLAYER AUTH, DOSSIER & MULTI-TABLE SYNC MIGRATION
-- Run this in your Supabase Dashboard -> SQL Editor (New Query -> Run)
-- ==============================================================================

-- 1. Ensure columns exist on public.players table
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS activision_id TEXT;
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS discord_name TEXT;
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS region TEXT DEFAULT 'NA East';
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS platform TEXT DEFAULT 'PC';
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS wins INT DEFAULT 0;
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS losses INT DEFAULT 0;
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS total_kills INT DEFAULT 0;
ALTER TABLE public.players ADD COLUMN IF NOT EXISTS total_deaths INT DEFAULT 0;

-- Create indexes on players for high-speed lookups
CREATE INDEX IF NOT EXISTS idx_players_user_id ON public.players(user_id);
CREATE INDEX IF NOT EXISTS idx_players_gamertag_lower ON public.players(LOWER(gamertag));
CREATE INDEX IF NOT EXISTS idx_players_activision ON public.players(activision_id);

-- 2. Ensure public.league_signups table exists with all required columns
CREATE TABLE IF NOT EXISTS public.league_signups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    gamertag TEXT NOT NULL,
    activision_id TEXT,
    discord_username TEXT NOT NULL,
    discord_user_id TEXT,
    role TEXT DEFAULT 'Flex',
    platform TEXT DEFAULT 'PC',
    region TEXT DEFAULT 'NA East',
    registration_type TEXT DEFAULT 'Free Agent',
    team_name TEXT,
    notes TEXT,
    status TEXT DEFAULT 'Pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Safely add any missing columns on league_signups
ALTER TABLE public.league_signups ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.league_signups ADD COLUMN IF NOT EXISTS discord_user_id TEXT;
ALTER TABLE public.league_signups ADD COLUMN IF NOT EXISTS activision_id TEXT;
ALTER TABLE public.league_signups ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'Flex';
ALTER TABLE public.league_signups ADD COLUMN IF NOT EXISTS platform TEXT DEFAULT 'PC';
ALTER TABLE public.league_signups ADD COLUMN IF NOT EXISTS region TEXT DEFAULT 'NA East';
ALTER TABLE public.league_signups ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Pending';

CREATE INDEX IF NOT EXISTS idx_league_signups_user_id ON public.league_signups(user_id);
CREATE INDEX IF NOT EXISTS idx_league_signups_gamertag ON public.league_signups(gamertag);

-- 3. Ensure public.arena_free_agents table exists with all required columns
CREATE TABLE IF NOT EXISTS public.arena_free_agents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT,
    gamertag TEXT NOT NULL UNIQUE,
    clan_tag VARCHAR(6) DEFAULT 'LFT',
    avatar_url TEXT DEFAULT 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=150&auto=format&fit=crop&q=80',
    ladder_pref TEXT NOT NULL DEFAULT '4v4_variant',
    primary_role TEXT DEFAULT 'Flex',
    secondary_role TEXT DEFAULT 'Main AR',
    elo INT DEFAULT 1200,
    kdr NUMERIC(4,2) DEFAULT 1.00,
    platform TEXT DEFAULT 'PC',
    region TEXT DEFAULT 'NA East',
    discord TEXT,
    activision_id TEXT,
    availability TEXT DEFAULT 'Active / Daily',
    bio TEXT DEFAULT 'Competitive operator looking for team.',
    mic BOOLEAN DEFAULT TRUE,
    is_active BOOLEAN DEFAULT TRUE,
    is_new_user BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.arena_free_agents ADD COLUMN IF NOT EXISTS user_id TEXT;
ALTER TABLE public.arena_free_agents ADD COLUMN IF NOT EXISTS activision_id TEXT;
ALTER TABLE public.arena_free_agents ADD COLUMN IF NOT EXISTS discord TEXT;
ALTER TABLE public.arena_free_agents ADD COLUMN IF NOT EXISTS primary_role TEXT DEFAULT 'Flex';
ALTER TABLE public.arena_free_agents ADD COLUMN IF NOT EXISTS platform TEXT DEFAULT 'PC';
ALTER TABLE public.arena_free_agents ADD COLUMN IF NOT EXISTS region TEXT DEFAULT 'NA East';

CREATE INDEX IF NOT EXISTS idx_arena_fa_gamertag ON public.arena_free_agents(gamertag);
CREATE INDEX IF NOT EXISTS idx_arena_fa_user_id ON public.arena_free_agents(user_id);

-- 4. Enable RLS and Configure Permissive Policies for Self-Registration
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.league_signups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.arena_free_agents ENABLE ROW LEVEL SECURITY;

-- Players Policies
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'players' AND policyname = 'Allow public select on players') THEN
        CREATE POLICY "Allow public select on players" ON public.players FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'players' AND policyname = 'Allow public insert on players') THEN
        CREATE POLICY "Allow public insert on players" ON public.players FOR INSERT WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'players' AND policyname = 'Allow public update on players') THEN
        CREATE POLICY "Allow public update on players" ON public.players FOR UPDATE USING (true);
    END IF;
END $$;

-- League Signups Policies
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'league_signups' AND policyname = 'Allow public select on league_signups') THEN
        CREATE POLICY "Allow public select on league_signups" ON public.league_signups FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'league_signups' AND policyname = 'Allow public insert on league_signups') THEN
        CREATE POLICY "Allow public insert on league_signups" ON public.league_signups FOR INSERT WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'league_signups' AND policyname = 'Allow public update on league_signups') THEN
        CREATE POLICY "Allow public update on league_signups" ON public.league_signups FOR UPDATE USING (true);
    END IF;
END $$;

-- Arena Free Agents Policies
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'arena_free_agents' AND policyname = 'Allow public select on arena_free_agents') THEN
        CREATE POLICY "Allow public select on arena_free_agents" ON public.arena_free_agents FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'arena_free_agents' AND policyname = 'Allow public insert on arena_free_agents') THEN
        CREATE POLICY "Allow public insert on arena_free_agents" ON public.arena_free_agents FOR INSERT WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'arena_free_agents' AND policyname = 'Allow public update on arena_free_agents') THEN
        CREATE POLICY "Allow public update on arena_free_agents" ON public.arena_free_agents FOR UPDATE USING (true);
    END IF;
END $$;

-- 5. Automatic Trigger Function: Handles new user signup on auth.users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
    d_tag TEXT;
    d_id TEXT;
    d_avatar TEXT;
    d_activision TEXT;
    d_role TEXT;
    d_region TEXT;
    d_platform TEXT;
BEGIN
    d_tag := COALESCE(
        new.raw_user_meta_data->>'gamertag',
        new.raw_user_meta_data->>'username',
        new.raw_user_meta_data->>'custom_claims'->>'global_name',
        new.raw_user_meta_data->>'full_name',
        new.raw_user_meta_data->>'name',
        new.raw_user_meta_data->>'user_name',
        split_part(new.email, '@', 1),
        'Operative'
    );
    
    d_id := COALESCE(
        new.raw_user_meta_data->>'provider_id',
        new.raw_user_meta_data->>'sub',
        new.raw_user_meta_data->>'discord_user_id'
    );

    d_activision := COALESCE(
        new.raw_user_meta_data->>'activision_id',
        NULL
    );

    d_role := COALESCE(
        new.raw_user_meta_data->>'role',
        new.raw_user_meta_data->>'tactical_role',
        'Flex'
    );

    d_region := COALESCE(
        new.raw_user_meta_data->>'region',
        'NA East'
    );

    d_platform := COALESCE(
        new.raw_user_meta_data->>'platform',
        'PC'
    );

    d_avatar := COALESCE(
        new.raw_user_meta_data->>'avatar_url',
        new.raw_user_meta_data->>'picture',
        'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=150&auto=format&fit=crop&q=80'
    );

    -- 1. Insert into league_signups
    INSERT INTO public.league_signups (
        user_id,
        gamertag,
        discord_username,
        discord_user_id,
        activision_id,
        role,
        platform,
        registration_type,
        region,
        notes,
        status,
        created_at
    )
    VALUES (
        new.id,
        d_tag,
        d_tag,
        d_id,
        d_activision,
        d_role,
        d_platform,
        'Free Agent',
        d_region,
        '[Auto-Created on Auth Registration]',
        'Pending',
        NOW()
    )
    ON CONFLICT DO NOTHING;

    -- 2. Insert into arena_free_agents
    INSERT INTO public.arena_free_agents (
        user_id,
        gamertag,
        activision_id,
        discord,
        primary_role,
        platform,
        region,
        avatar_url,
        elo,
        kdr,
        ladder_pref,
        is_active,
        is_new_user,
        created_at
    )
    VALUES (
        new.id::text,
        d_tag,
        d_activision,
        d_tag,
        d_role,
        d_platform,
        d_region,
        d_avatar,
        1200,
        1.00,
        '4v4_variant',
        true,
        true,
        NOW()
    )
    ON CONFLICT (gamertag) DO UPDATE SET
        activision_id = COALESCE(EXCLUDED.activision_id, arena_free_agents.activision_id),
        discord = COALESCE(EXCLUDED.discord, arena_free_agents.discord),
        primary_role = EXCLUDED.primary_role,
        platform = EXCLUDED.platform,
        region = EXCLUDED.region,
        updated_at = NOW();

    -- 3. Insert into players (if not existing)
    INSERT INTO public.players (
        user_id,
        gamertag,
        activision_id,
        discord_name,
        role,
        region,
        platform,
        avatar_url,
        kdr,
        wins,
        losses,
        total_kills,
        total_deaths,
        created_at
    )
    VALUES (
        new.id,
        d_tag,
        d_activision,
        d_tag,
        d_role,
        d_region,
        d_platform,
        d_avatar,
        1.00,
        0,
        0,
        0,
        0,
        NOW()
    )
    ON CONFLICT (gamertag) DO UPDATE SET
        activision_id = COALESCE(EXCLUDED.activision_id, players.activision_id),
        role = EXCLUDED.role,
        region = EXCLUDED.region,
        platform = EXCLUDED.platform,
        discord_name = COALESCE(EXCLUDED.discord_name, players.discord_name);

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Reattach trigger to auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
