-- ==============================================================================
-- FRONTLINE CALL OF DUTY LEAGUE - PLAYER STATS & WIN/LOSS COLUMNS MIGRATION
-- Run this script in your Supabase Dashboard -> SQL Editor (New Query -> Run)
-- ==============================================================================

-- 1. Add wins and losses tracking to players table (if not already present)
ALTER TABLE players ADD COLUMN IF NOT EXISTS wins INT DEFAULT 0;
ALTER TABLE players ADD COLUMN IF NOT EXISTS losses INT DEFAULT 0;

-- 2. Ensure player_map_stats table exists
CREATE TABLE IF NOT EXISTS player_map_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT REFERENCES players(id) ON DELETE CASCADE,
    map_name TEXT NOT NULL,
    game_mode TEXT NOT NULL,
    opponent_team TEXT,
    kills INT DEFAULT 0,
    deaths INT DEFAULT 0,
    damage INT DEFAULT 0,
    kdr NUMERIC(4, 2) DEFAULT 1.00,
    result TEXT DEFAULT 'W',
    score TEXT,
    match_date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Enable Row Level Security (RLS) on player_map_stats
ALTER TABLE player_map_stats ENABLE ROW LEVEL SECURITY;

-- 4. Allow public read access on player_map_stats
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'player_map_stats' 
        AND policyname = 'Allow public read access on player_map_stats'
    ) THEN
        CREATE POLICY "Allow public read access on player_map_stats" ON player_map_stats
            FOR SELECT USING (true);
    END IF;
END $$;

-- 5. Enable full admin write access on player_map_stats (INSERT, UPDATE, DELETE)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'player_map_stats' 
        AND policyname = 'Enable all access on player_map_stats'
    ) THEN
        CREATE POLICY "Enable all access on player_map_stats" ON player_map_stats
            FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;

-- 6. Ensure full admin write access on players
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'players' 
        AND policyname = 'Enable all access on players'
    ) THEN
        CREATE POLICY "Enable all access on players" ON players
            FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;
