-- ==============================================================================
-- FRONTLINE CALL OF DUTY LEAGUE - ORGANIZATION & TEAM SIGNUPS TABLE
-- (Copy and run this in your Supabase Dashboard -> SQL Editor)
-- ==============================================================================

-- 1. Create org_signups table
CREATE TABLE IF NOT EXISTS org_signups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_name TEXT NOT NULL,
    team_tag VARCHAR(6) NOT NULL,                  -- e.g. "NSH", "VTG", "FAZE"
    owner_gamertag TEXT NOT NULL,
    owner_discord TEXT NOT NULL,
    contact_email TEXT NOT NULL,
    region TEXT DEFAULT 'NA East',                 -- NA East, NA Central, NA West, EU, Other
    logo_url TEXT,
    twitter_handle TEXT,
    
    -- Starting 4-Man Roster
    player_1_gamertag TEXT NOT NULL,
    player_1_activision TEXT,
    player_1_role TEXT DEFAULT 'SMG',
    
    player_2_gamertag TEXT NOT NULL,
    player_2_activision TEXT,
    player_2_role TEXT DEFAULT 'Main AR',
    
    player_3_gamertag TEXT NOT NULL,
    player_3_activision TEXT,
    player_3_role TEXT DEFAULT 'Flex',
    
    player_4_gamertag TEXT NOT NULL,
    player_4_activision TEXT,
    player_4_role TEXT DEFAULT 'SMG',
    
    substitute_gamertag TEXT,
    substitute_activision TEXT,
    
    -- Financials & Payment Verification
    entry_fee_amount NUMERIC(6,2) DEFAULT 25.00,
    payment_method TEXT DEFAULT 'PayPal',
    payment_status TEXT DEFAULT 'Pending Payment', -- 'Pending Payment', 'Paid', 'Refunded'
    paypal_transaction_id TEXT,
    reference_code TEXT UNIQUE,                    -- e.g. "FRT-ORG-8492"
    approval_status TEXT DEFAULT 'Pending Review',  -- 'Pending Review', 'Approved', 'Waitlist'
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE org_signups ENABLE ROW LEVEL SECURITY;

-- 3. Setup RLS Policies (Allow public signups and public read)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'org_signups' 
        AND policyname = 'Allow public insert on org_signups'
    ) THEN
        CREATE POLICY "Allow public insert on org_signups" ON org_signups
            FOR INSERT WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'org_signups' 
        AND policyname = 'Allow public read on org_signups'
    ) THEN
        CREATE POLICY "Allow public read on org_signups" ON org_signups
            FOR SELECT USING (true);
    END IF;
END
$$;
