-- ==============================================================================
-- FRONTLINE CALL OF DUTY LEAGUE - ANNOUNCEMENTS TABLE & PERMISSIONS
-- Run this script in your Supabase Dashboard -> SQL Editor (New Query -> Run)
-- ==============================================================================

-- 1. Create Announcements Table
CREATE TABLE IF NOT EXISTS league_announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    tag TEXT DEFAULT 'Official Update',
    tag_color TEXT DEFAULT 'lime',           -- 'lime', 'amber', 'red', 'cyan'
    link_url TEXT,
    link_text TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    pinned BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE league_announcements ENABLE ROW LEVEL SECURITY;

-- 3. Allow Public Read Access (so index.html visitors see the announcements)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'league_announcements' 
        AND policyname = 'Allow public read on league_announcements'
    ) THEN
        CREATE POLICY "Allow public read on league_announcements" ON league_announcements
            FOR SELECT USING (true);
    END IF;
END $$;

-- 4. Enable Full Admin Write Access (INSERT, UPDATE, DELETE for admin console)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'league_announcements' 
        AND policyname = 'Enable all access on league_announcements'
    ) THEN
        CREATE POLICY "Enable all access on league_announcements" ON league_announcements
            FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;

-- 5. Seed default initial announcement if table is empty
INSERT INTO league_announcements (title, message, tag, tag_color, link_url, link_text, is_active, pinned)
SELECT 
    'Season 1 Official Bracket Seeding & Roster Lock',
    'Rosters for Season 1 lock this Friday at 11:59 PM EST. Team captains must ensure all player Activision IDs and roles are confirmed in the recruitment terminal before seedings are locked.',
    'Tournament Alert',
    'lime',
    'brackets.html',
    'View Tournament Brackets ↗',
    true,
    true
WHERE NOT EXISTS (SELECT 1 FROM league_announcements);
