-- ==============================================================================
-- ADD TEAM MAP STATS & TELEMETRY TABLE TO SUPABASE DATABASE
-- (Copy and run this in Supabase -> SQL Editor)
-- ==============================================================================

-- 1. Create Team Map Records Table
CREATE TABLE IF NOT EXISTS team_map_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT REFERENCES teams(id) ON DELETE CASCADE,
    map_name TEXT NOT NULL,       -- e.g. "Karachi", "Sub Base", "Rio", "Highrise", "6 Star", "Terminal", "Invasion"
    game_mode TEXT NOT NULL,      -- e.g. "Hardpoint", "Search & Destroy", "Control"
    wins INT DEFAULT 0,
    losses INT DEFAULT 0,
    win_rate INT DEFAULT 0,
    streak TEXT DEFAULT '1W',
    recent_score TEXT,            -- e.g. '250 - 210 vs Vantage'
    recent_result TEXT DEFAULT 'W',-- 'W' or 'L'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE team_map_records ENABLE ROW LEVEL SECURITY;

-- 3. Allow Public Read Access
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'team_map_records' 
        AND policyname = 'Allow public read access on team_map_records'
    ) THEN
        CREATE POLICY "Allow public read access on team_map_records" ON team_map_records
            FOR SELECT USING (true);
    END IF;
END
$$;

-- 4. Insert Sample Team Map Records
INSERT INTO team_map_records (team_id, map_name, game_mode, wins, losses, win_rate, streak, recent_score, recent_result) VALUES
-- Night Shift (NSH)
((SELECT id FROM teams WHERE name = 'Night Shift' LIMIT 1), 'Karachi', 'Hardpoint', 3, 0, 100, '3W', '250 - 210 vs Vantage', 'W'),
((SELECT id FROM teams WHERE name = 'Night Shift' LIMIT 1), 'Sub Base', 'Hardpoint', 2, 1, 67, '1W', '250 - 195 vs Redline', 'W'),
((SELECT id FROM teams WHERE name = 'Night Shift' LIMIT 1), 'Rio', 'Hardpoint', 2, 1, 67, '2W', '250 - 225 vs Static', 'W'),
((SELECT id FROM teams WHERE name = 'Night Shift' LIMIT 1), 'Highrise', 'Search & Destroy', 3, 0, 100, '3W', '6 - 4 vs Vantage', 'W'),
((SELECT id FROM teams WHERE name = 'Night Shift' LIMIT 1), 'Rio', 'Search & Destroy', 2, 0, 100, '2W', '6 - 2 vs Redline', 'W'),
((SELECT id FROM teams WHERE name = 'Night Shift' LIMIT 1), 'Karachi', 'Search & Destroy', 0, 1, 0, '1L', '4 - 6 vs Vantage', 'L'),
((SELECT id FROM teams WHERE name = 'Night Shift' LIMIT 1), 'Invasion', 'Control', 2, 2, 50, '1L', '2 - 3 vs Vantage', 'L'),
((SELECT id FROM teams WHERE name = 'Night Shift' LIMIT 1), 'Highrise', 'Control', 2, 1, 67, '1W', '3 - 1 vs Redline', 'W'),

-- Vantage (VTG)
((SELECT id FROM teams WHERE name = 'Vantage' LIMIT 1), 'Karachi', 'Hardpoint', 2, 2, 50, '1L', '210 - 250 vs Night Shift', 'L'),
((SELECT id FROM teams WHERE name = 'Vantage' LIMIT 1), '6 Star', 'Hardpoint', 2, 1, 67, '2W', '250 - 180 vs Static', 'W'),
((SELECT id FROM teams WHERE name = 'Vantage' LIMIT 1), 'Vista', 'Hardpoint', 1, 1, 50, '1W', '250 - 220 vs Redline', 'W'),
((SELECT id FROM teams WHERE name = 'Vantage' LIMIT 1), 'Highrise', 'Search & Destroy', 2, 2, 50, '1L', '4 - 6 vs Night Shift', 'L'),
((SELECT id FROM teams WHERE name = 'Vantage' LIMIT 1), 'Karachi', 'Search & Destroy', 2, 0, 100, '2W', '6 - 4 vs Night Shift', 'W'),
((SELECT id FROM teams WHERE name = 'Vantage' LIMIT 1), 'Terminal', 'Search & Destroy', 1, 1, 50, '1W', '6 - 3 vs Redline', 'W'),
((SELECT id FROM teams WHERE name = 'Vantage' LIMIT 1), 'Invasion', 'Control', 3, 1, 75, '2W', '3 - 2 vs Night Shift', 'W'),
((SELECT id FROM teams WHERE name = 'Vantage' LIMIT 1), 'Highrise', 'Control', 1, 1, 50, '1L', '1 - 3 vs Redline', 'L'),

-- Redline (RED)
((SELECT id FROM teams WHERE name = 'Redline' LIMIT 1), 'Sub Base', 'Hardpoint', 1, 2, 33, '1L', '195 - 250 vs Night Shift', 'L'),
((SELECT id FROM teams WHERE name = 'Redline' LIMIT 1), 'Karachi', 'Hardpoint', 2, 1, 67, '1W', '250 - 220 vs Static', 'W'),
((SELECT id FROM teams WHERE name = 'Redline' LIMIT 1), 'Rio', 'Hardpoint', 1, 2, 33, '1L', '215 - 250 vs Vantage', 'L'),
((SELECT id FROM teams WHERE name = 'Redline' LIMIT 1), 'Rio', 'Search & Destroy', 1, 2, 33, '1L', '2 - 6 vs Night Shift', 'L'),
((SELECT id FROM teams WHERE name = 'Redline' LIMIT 1), 'Karachi', 'Search & Destroy', 2, 1, 67, '1W', '6 - 4 vs Night Shift', 'W'),
((SELECT id FROM teams WHERE name = 'Redline' LIMIT 1), 'Highrise', 'Search & Destroy', 1, 1, 50, '1W', '6 - 5 vs Static', 'W'),
((SELECT id FROM teams WHERE name = 'Redline' LIMIT 1), 'Highrise', 'Control', 2, 1, 67, '1W', '3 - 1 vs Vantage', 'W'),
((SELECT id FROM teams WHERE name = 'Redline' LIMIT 1), 'Invasion', 'Control', 1, 2, 33, '1L', '1 - 3 vs Night Shift', 'L'),

-- Static (STC)
((SELECT id FROM teams WHERE name = 'Static' LIMIT 1), '6 Star', 'Hardpoint', 1, 2, 33, '1L', '180 - 250 vs Vantage', 'L'),
((SELECT id FROM teams WHERE name = 'Static' LIMIT 1), 'Karachi', 'Hardpoint', 1, 2, 33, '1L', '220 - 250 vs Redline', 'L'),
((SELECT id FROM teams WHERE name = 'Static' LIMIT 1), 'Sub Base', 'Hardpoint', 1, 2, 33, '1W', '250 - 235 vs Redline', 'W'),
((SELECT id FROM teams WHERE name = 'Static' LIMIT 1), 'Highrise', 'Search & Destroy', 1, 2, 33, '1L', '5 - 6 vs Redline', 'L'),
((SELECT id FROM teams WHERE name = 'Static' LIMIT 1), 'Terminal', 'Search & Destroy', 1, 2, 33, '1L', '3 - 6 vs Vantage', 'L'),
((SELECT id FROM teams WHERE name = 'Static' LIMIT 1), 'Invasion', 'Control', 1, 2, 33, '1W', '3 - 2 vs Redline', 'W'),
((SELECT id FROM teams WHERE name = 'Static' LIMIT 1), 'Highrise', 'Control', 1, 3, 25, '2L', '0 - 3 vs Night Shift', 'L');
