-- ==============================================================================
-- FRONTLINE CALL OF DUTY LEAGUE - REGISTRATION / SIGNUPS TABLE
-- (Copy and run this in your Supabase Dashboard -> SQL Editor)
-- ==============================================================================

-- 1. Create league signups table
CREATE TABLE IF NOT EXISTS league_signups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gamertag TEXT NOT NULL,
    activision_id TEXT,
    discord_username TEXT NOT NULL,
    discord_user_id TEXT UNIQUE,                   -- Unique Discord snowflake ID from Discord Bot
    role TEXT DEFAULT 'Flex',                      -- SMG, Main AR, Flex, Sniper
    platform TEXT DEFAULT 'PC',                    -- PC, PlayStation, Xbox
    registration_type TEXT DEFAULT 'Free Agent',   -- 'Free Agent' or 'Team Captain'
    team_name TEXT,                                -- If registering a squad
    region TEXT DEFAULT 'NA East',                 -- NA East, NA Central, NA West, EU, Other
    notes TEXT,                                    -- Additional player notes or experience
    status TEXT DEFAULT 'Pending',                 -- 'Pending', 'Approved', 'Waitlist'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE league_signups ENABLE ROW LEVEL SECURITY;

-- 3. Allow Public Insert, Public Read, and Full Admin Access (Delete & Update)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'league_signups' 
        AND policyname = 'Allow public insert on league_signups'
    ) THEN
        CREATE POLICY "Allow public insert on league_signups" ON league_signups
            FOR INSERT WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'league_signups' 
        AND policyname = 'Allow public read on league_signups'
    ) THEN
        CREATE POLICY "Allow public read on league_signups" ON league_signups
            FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'league_signups' 
        AND policyname = 'Allow all access on league_signups'
    ) THEN
        CREATE POLICY "Allow all access on league_signups" ON league_signups
            FOR ALL USING (true) WITH CHECK (true);
    END IF;
END
$$;
