-- ==============================================================================
-- FRONTLINE CALL OF DUTY LEAGUE - TOURNAMENT BRACKETS & DIVISIONS SCHEMA
-- (Copy and run this in your Supabase Dashboard -> SQL Editor to enable dynamic brackets)
-- ==============================================================================

-- 1. Create tournament_divisions table
CREATE TABLE IF NOT EXISTS tournament_divisions (
    id TEXT PRIMARY KEY,                             -- 'premier', 'challengers', 'open'
    name TEXT NOT NULL,                              -- e.g. 'Premier Championship'
    tier TEXT DEFAULT 'Division 1',                  -- 'Division 1', 'Division 2', 'Division 3'
    format TEXT DEFAULT 'Double Elimination (Bo5)',  -- Format summary
    prize_pool TEXT DEFAULT '$1,000 USD',
    season TEXT DEFAULT 'Season 1',
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create tournament_matches table
CREATE TABLE IF NOT EXISTS tournament_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    division_id TEXT REFERENCES tournament_divisions(id) ON DELETE CASCADE,
    match_code TEXT NOT NULL,                        -- e.g. 'M1', 'UB-QF-1', 'WF', 'GF'
    round_name TEXT NOT NULL,                        -- e.g. 'Upper Quarterfinals', 'Winners Finals'
    stage TEXT NOT NULL,                             -- 'winners', 'elimination', 'finals'
    round_order INT DEFAULT 1,                       -- 1 for QF, 2 for SF, 3 for Finals
    match_order INT DEFAULT 1,                       -- Order within the round
    
    -- Competitor 1
    team1_name TEXT NOT NULL,
    team1_tag TEXT NOT NULL,
    team1_seed INT,
    team1_score INT DEFAULT 0,
    
    -- Competitor 2
    team2_name TEXT NOT NULL,
    team2_tag TEXT NOT NULL,
    team2_seed INT,
    team2_score INT DEFAULT 0,
    
    -- Outcome & Scheduling
    winner_name TEXT,
    status TEXT DEFAULT 'Scheduled',                 -- 'Completed', 'Live', 'Scheduled'
    scheduled_time TEXT,                             -- e.g. 'Fri 7:00 PM EST'
    best_of INT DEFAULT 5,                           -- 3 or 5
    mvp_gamertag TEXT,
    mvp_stats TEXT,
    vod_url TEXT,
    maps_data JSONB,                                 -- Array of map breakdown details
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE tournament_divisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE tournament_matches ENABLE ROW LEVEL SECURITY;

-- 4. Allow Public Read Access
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'tournament_divisions' 
        AND policyname = 'Allow public read on tournament_divisions'
    ) THEN
        CREATE POLICY "Allow public read on tournament_divisions" ON tournament_divisions
            FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'tournament_matches' 
        AND policyname = 'Allow public read on tournament_matches'
    ) THEN
        CREATE POLICY "Allow public read on tournament_matches" ON tournament_matches
            FOR SELECT USING (true);
    END IF;
END $$;

-- 5. Seed Divisions
INSERT INTO tournament_divisions (id, name, tier, format, prize_pool, description) VALUES
('premier', 'Premier Championship', 'Division 1', 'Double Elimination (Best of 5)', '$1,000 USD', 'Top 8 franchise squads fighting in the official Frontline Championship Series double-elimination bracket.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO tournament_divisions (id, name, tier, format, prize_pool, description) VALUES
('challengers', 'Challengers Division', 'Division 2', 'Double Elimination (Best of 5)', '$500 USD', 'Tier-2 contenders fighting for season promotion and the official Challengers Cup.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO tournament_divisions (id, name, tier, format, prize_pool, description) VALUES
('open', 'Open Recruit Cup', 'Division 3', 'Single Elimination (Best of 3)', '$250 USD', 'Grassroots open tournament for free agent draft teams, community rosters, and rookie contenders.')
ON CONFLICT (id) DO NOTHING;
