-- ==============================================================================
-- FRONTLINE CALL OF DUTY LEAGUE - LADDER ARENA & ELO SYSTEM SCHEMA
-- ==============================================================================
-- Copy and paste this script into your Supabase Dashboard -> SQL Editor -> Run
-- This establishes the completely independent Ladder ecosystem (separate from League)
-- ==============================================================================

-- 1. CREATE LADDER TEAMS TABLE
CREATE TABLE IF NOT EXISTS ladder_teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    tag VARCHAR(6) NOT NULL,
    avatar_url TEXT,
    ladder_type TEXT NOT NULL DEFAULT '4v4_variant', -- '4v4_variant', '2v2_snd', '1v1_radar'
    captain_name TEXT NOT NULL,
    captain_discord TEXT,
    elo INT DEFAULT 1200,
    tier TEXT DEFAULT 'Operator',                   -- 'Recruit', 'Operator', 'Specialist', 'Vanguard', 'Warlord', 'Commander', 'Apex Prestige'
    wins INT DEFAULT 0,
    losses INT DEFAULT 0,
    streak INT DEFAULT 0,                           -- e.g. positive for win streak (+3), negative or 0 for loss
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. CREATE LADDER ROSTERS TABLE
CREATE TABLE IF NOT EXISTS ladder_rosters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT REFERENCES ladder_teams(id) ON DELETE CASCADE,
    gamertag TEXT NOT NULL,
    discord_username TEXT,
    role TEXT DEFAULT 'member',                     -- 'captain', 'member'
    joined_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. CREATE LADDER MATCHES TABLE
CREATE TABLE IF NOT EXISTS ladder_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ladder_type TEXT NOT NULL DEFAULT '4v4_variant',
    team_a_id BIGINT REFERENCES ladder_teams(id) ON DELETE CASCADE,
    team_b_id BIGINT REFERENCES ladder_teams(id) ON DELETE SET NULL,
    team_a_score INT DEFAULT 0,
    team_b_score INT DEFAULT 0,
    best_of INT DEFAULT 5,                          -- BO3 or BO5
    status TEXT DEFAULT 'open',                     -- 'open', 'accepted', 'in_progress', 'completed', 'disputed', 'cancelled'
    scheduled_time TIMESTAMPTZ DEFAULT NOW(),
    winner_id BIGINT REFERENCES ladder_teams(id) ON DELETE SET NULL,
    reported_by TEXT,
    proof_url TEXT,
    notes TEXT,
    maps_played JSONB,                             -- e.g. [{"map": "Karachi", "mode": "Hardpoint", "winner": "team_a"}]
    elo_change INT DEFAULT 25,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ
);

-- 4. CREATE LADDER DISPUTES TABLE
CREATE TABLE IF NOT EXISTS ladder_disputes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT REFERENCES ladder_matches(id) ON DELETE CASCADE,
    submitted_by TEXT NOT NULL,
    dispute_reason TEXT NOT NULL,
    proof_url TEXT,
    status TEXT DEFAULT 'open',                     -- 'open', 'under_review', 'resolved', 'dismissed'
    admin_notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    resolved_at TIMESTAMPTZ
);

-- ==============================================================================
-- 5. ENABLE ROW LEVEL SECURITY (RLS) & PUBLIC ACCESS POLICIES
-- ==============================================================================
ALTER TABLE ladder_teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE ladder_rosters ENABLE ROW LEVEL SECURITY;
ALTER TABLE ladder_matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE ladder_disputes ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    -- ladder_teams policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ladder_teams' AND policyname = 'Allow public select on ladder_teams') THEN
        CREATE POLICY "Allow public select on ladder_teams" ON ladder_teams FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ladder_teams' AND policyname = 'Allow public insert on ladder_teams') THEN
        CREATE POLICY "Allow public insert on ladder_teams" ON ladder_teams FOR INSERT WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ladder_teams' AND policyname = 'Allow public update on ladder_teams') THEN
        CREATE POLICY "Allow public update on ladder_teams" ON ladder_teams FOR UPDATE USING (true);
    END IF;

    -- ladder_rosters policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ladder_rosters' AND policyname = 'Allow public select on ladder_rosters') THEN
        CREATE POLICY "Allow public select on ladder_rosters" ON ladder_rosters FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ladder_rosters' AND policyname = 'Allow public insert on ladder_rosters') THEN
        CREATE POLICY "Allow public insert on ladder_rosters" ON ladder_rosters FOR INSERT WITH CHECK (true);
    END IF;

    -- ladder_matches policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ladder_matches' AND policyname = 'Allow public select on ladder_matches') THEN
        CREATE POLICY "Allow public select on ladder_matches" ON ladder_matches FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ladder_matches' AND policyname = 'Allow public insert on ladder_matches') THEN
        CREATE POLICY "Allow public insert on ladder_matches" ON ladder_matches FOR INSERT WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ladder_matches' AND policyname = 'Allow public update on ladder_matches') THEN
        CREATE POLICY "Allow public update on ladder_matches" ON ladder_matches FOR UPDATE USING (true);
    END IF;

    -- ladder_disputes policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ladder_disputes' AND policyname = 'Allow public select on ladder_disputes') THEN
        CREATE POLICY "Allow public select on ladder_disputes" ON ladder_disputes FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ladder_disputes' AND policyname = 'Allow public insert on ladder_disputes') THEN
        CREATE POLICY "Allow public insert on ladder_disputes" ON ladder_disputes FOR INSERT WITH CHECK (true);
    END IF;
END $$;

-- ==============================================================================
-- 6. SEED INITIAL SAMPLE LADDER SQUADS (4v4 Variant, 2v2 SnD, 1v1 Radar)
-- ==============================================================================

-- 4v4 Variant Teams
INSERT INTO ladder_teams (name, tag, avatar_url, ladder_type, captain_name, captain_discord, elo, tier, wins, losses, streak)
VALUES 
('Apex Predators', 'APEX', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=150&auto=format&fit=crop&q=80', '4v4_variant', 'ViperX', 'viperx#0001', 2045, 'Apex Prestige', 18, 2, 6),
('Crimson Syndicate', 'CRIM', 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=150&auto=format&fit=crop&q=80', '4v4_variant', 'Havoc', 'havoc#4421', 1880, 'Commander', 14, 4, 3),
('Ghost Protocol', 'GPRT', 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=150&auto=format&fit=crop&q=80', '4v4_variant', 'Specter', 'specter#1999', 1690, 'Warlord', 11, 5, 2),
('Vanguard Prime', 'VNG', 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=150&auto=format&fit=crop&q=80', '4v4_variant', 'Phantom', 'phantom#8821', 1520, 'Vanguard', 9, 6, 1),
('Sub Base Kings', 'SBK', 'https://images.unsplash.com/photo-1563089145-599997674d42?w=150&auto=format&fit=crop&q=80', '4v4_variant', 'Blitz', 'blitz#3123', 1340, 'Specialist', 7, 7, 0),
('Rookie Regime', 'RREG', 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80', '4v4_variant', 'NewbieSniper', 'newb#9981', 1120, 'Operator', 3, 6, -1);

-- 2v2 SnD Duos
INSERT INTO ladder_teams (name, tag, avatar_url, ladder_type, captain_name, captain_discord, elo, tier, wins, losses, streak)
VALUES 
('Duo Demons', 'DEMN', 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80', '2v2_snd', 'Reaper', 'reaper#5555', 1950, 'Commander', 15, 3, 5),
('Silent Scope Duo', 'SSD', 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=150&auto=format&fit=crop&q=80', '2v2_snd', 'DeadSilence', 'deadsilence#1212', 1740, 'Warlord', 12, 4, 2),
('Bomb Site Rushers', 'BSR', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=150&auto=format&fit=crop&q=80', '2v2_snd', 'NinjaDefuse', 'ninja#0042', 1480, 'Vanguard', 8, 5, 1);

-- 1v1 Radar / Gunfight
INSERT INTO ladder_teams (name, tag, avatar_url, ladder_type, captain_name, captain_discord, elo, tier, wins, losses, streak)
VALUES 
('Lone Wolf Solo', 'LONE', 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=150&auto=format&fit=crop&q=80', '1v1_radar', 'Apex', 'apex#0001', 2010, 'Apex Prestige', 22, 1, 8),
('QuickScopeGod', 'QSG', 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=150&auto=format&fit=crop&q=80', '1v1_radar', 'Pulse', 'pulse#7777', 1675, 'Warlord', 13, 7, 3);

-- Seed Sample Open Challenges
INSERT INTO ladder_matches (ladder_type, team_a_id, best_of, status, scheduled_time, notes)
VALUES 
('4v4_variant', (SELECT id FROM ladder_teams WHERE tag = 'CRIM'), 5, 'open', NOW() + INTERVAL '2 hours', 'Looking for Top 10 Squad. CDL Rules, Karachi/Sub Base.'),
('2v2_snd', (SELECT id FROM ladder_teams WHERE tag = 'DEMN'), 3, 'open', NOW() + INTERVAL '4 hours', '2v2 SnD Any Map. Central host preferred.'),
('1v1_radar', (SELECT id FROM ladder_teams WHERE tag = 'QSG'), 3, 'open', NOW() + INTERVAL '1 hour', '1v1 Rust/Shipment Snipers Only.');

-- Seed Sample Dispute for Admin Review Testing
INSERT INTO ladder_disputes (match_id, submitted_by, dispute_reason, proof_url, status)
VALUES
(1, 'Automated System (Score Conflict)', 'Automated Dispute: Score Conflict. Apex Predators reported 3-1, while Crimson Syndicate reported 1-3.', 'https://twitch.tv/videos/sample_match_vod', 'open');
