-- ==============================================================================
-- FRONTLINE ARENA - FREE AGENT (LFT) RECRUITMENT DIRECTORY SCHEMA
-- ==============================================================================
-- Copy and run this script in your Supabase Dashboard -> SQL Editor -> Run
-- This table stores all Arena free agents, both manually submitted LFT cards
-- and new users who register an account on the website.
-- ==============================================================================

-- 1. CREATE ARENA FREE AGENTS TABLE
CREATE TABLE IF NOT EXISTS arena_free_agents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT,                                      -- Website / Supabase Auth ID if registered
    gamertag TEXT NOT NULL UNIQUE,                     -- Operator gamertag / website username
    clan_tag VARCHAR(6) DEFAULT 'LFT',                 -- Clan or recruitment tag
    avatar_url TEXT DEFAULT 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=150&auto=format&fit=crop&q=80',
    ladder_pref TEXT NOT NULL DEFAULT '4v4_variant',   -- '4v4_variant', '2v2_snd', '1v1_radar', 'all'
    primary_role TEXT DEFAULT 'Flex',                  -- 'Main AR', 'SMG Slayer', 'Entry Sub', 'Flex', 'Sniper / Search'
    secondary_role TEXT DEFAULT 'Main AR',
    elo INT DEFAULT 1200,                              -- ELO / Ladder Rating
    kdr NUMERIC(4,2) DEFAULT 1.15,                     -- Kill / Death Ratio
    platform TEXT DEFAULT 'Crossplay',                 -- 'PC', 'PlayStation 5', 'Xbox Series X', 'Crossplay'
    region TEXT DEFAULT 'NA East',                     -- 'NA East', 'NA Central', 'NA West', 'Europe'
    discord TEXT,                                      -- Discord tag (e.g. tag#0001)
    activision_id TEXT,                                -- Activision ID (e.g. Gamertag#1234567)
    availability TEXT DEFAULT 'Active / Daily',        -- Play schedule
    bio TEXT DEFAULT 'Competitive operator looking for team.',
    mic BOOLEAN DEFAULT TRUE,
    is_active BOOLEAN DEFAULT TRUE,
    is_new_user BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. CREATE PERFORMANCE INDEXES
CREATE INDEX IF NOT EXISTS idx_arena_fa_ladder_pref ON arena_free_agents(ladder_pref);
CREATE INDEX IF NOT EXISTS idx_arena_fa_elo ON arena_free_agents(elo DESC);
CREATE INDEX IF NOT EXISTS idx_arena_fa_active ON arena_free_agents(is_active);

-- 3. ENABLE ROW LEVEL SECURITY (RLS)
ALTER TABLE arena_free_agents ENABLE ROW LEVEL SECURITY;

-- 4. PUBLIC ACCESS POLICIES
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'arena_free_agents' 
        AND policyname = 'Allow public select on arena_free_agents'
    ) THEN
        CREATE POLICY "Allow public select on arena_free_agents" 
            ON arena_free_agents FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'arena_free_agents' 
        AND policyname = 'Allow public insert on arena_free_agents'
    ) THEN
        CREATE POLICY "Allow public insert on arena_free_agents" 
            ON arena_free_agents FOR INSERT WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'arena_free_agents' 
        AND policyname = 'Allow public update on arena_free_agents'
    ) THEN
        CREATE POLICY "Allow public update on arena_free_agents" 
            ON arena_free_agents FOR UPDATE USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'arena_free_agents' 
        AND policyname = 'Allow public delete on arena_free_agents'
    ) THEN
        CREATE POLICY "Allow public delete on arena_free_agents" 
            ON arena_free_agents FOR DELETE USING (true);
    END IF;
END $$;

-- 5. INITIAL STATE
-- Free agents are registered organically via the Free Agent Board (arena-free-agents.html) or OAuth registration.

