-- ==============================================================================
-- FRONTLINE CALL OF DUTY LEAGUE - LADDER ARENA & ELO SYSTEM SCHEMA
-- ==============================================================================
-- Copy and paste this script into your Supabase Dashboard -> SQL Editor -> Run
-- This establishes the completely independent Ladder ecosystem (separate from League)
-- ==============================================================================

-- 1. CREATE LADDER TEAMS TABLE
CREATE TABLE IF NOT EXISTS ladder_teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    tag VARCHAR(6) NOT NULL,
    avatar_url TEXT,
    ladder_type TEXT NOT NULL DEFAULT '4v4_variant', -- '4v4_variant', '2v2_snd', '1v1_radar'
    captain_name TEXT NOT NULL,
    captain_discord TEXT,
    elo INT DEFAULT 1200,
    tier TEXT DEFAULT 'Operator',                   -- 'Recruit', 'Operator', 'Specialist', 'Vanguard', 'Warlord', 'Commander', 'Apex Prestige'
    wins INT DEFAULT 0,
    losses INT DEFAULT 0,
    streak INT DEFAULT 0,                           -- e.g. positive for win streak (+3), negative or 0 for loss
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. CREATE LADDER ROSTERS TABLE
CREATE TABLE IF NOT EXISTS ladder_rosters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT REFERENCES ladder_teams(id) ON DELETE CASCADE,
    gamertag TEXT NOT NULL,
    discord_username TEXT,
    role TEXT DEFAULT 'member',                     -- 'captain', 'member'
    joined_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. CREATE LADDER MATCHES TABLE
CREATE TABLE IF NOT EXISTS ladder_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ladder_type TEXT NOT NULL DEFAULT '4v4_variant',
    team_a_id BIGINT REFERENCES ladder_teams(id) ON DELETE CASCADE,
    team_b_id BIGINT REFERENCES ladder_teams(id) ON DELETE SET NULL,
    team_a_score INT DEFAULT 0,
    team_b_score INT DEFAULT 0,
    best_of INT DEFAULT 5,                          -- BO3 or BO5
    status TEXT DEFAULT 'open',                     -- 'open', 'accepted', 'in_progress', 'completed', 'disputed', 'cancelled'
    scheduled_time TIMESTAMPTZ DEFAULT NOW(),
    winner_id BIGINT REFERENCES ladder_teams(id) ON DELETE SET NULL,
    reported_by TEXT,
    proof_url TEXT,
    notes TEXT,
    maps_played JSONB,                             -- e.g. [{"map": "Karachi", "mode": "Hardpoint", "winner": "team_a"}]
    elo_change INT DEFAULT 25,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ
);

-- 4. CREATE LADDER DISPUTES TABLE
CREATE TABLE IF NOT EXISTS ladder_disputes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT REFERENCES ladder_matches(id) ON DELETE CASCADE,
    submitted_by TEXT NOT NULL,
    dispute_reason TEXT NOT NULL,
    proof_url TEXT,
    status TEXT DEFAULT 'open',                     -- 'open', 'under_review', 'resolved', 'dismissed'
    admin_notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    resolved_at TIMESTAMPTZ
);

-- 5. CREATE ARENA FREE AGENTS (LFT) TABLE
CREATE TABLE IF NOT EXISTS arena_free_agents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT,                                      -- Website / Supabase Auth ID if registered
    gamertag TEXT NOT NULL UNIQUE,                     -- Operator gamertag / website username
    clan_tag VARCHAR(6) DEFAULT 'LFT',                 -- Clan or recruitment tag
    avatar_url TEXT DEFAULT 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=150&auto=format&fit=crop&q=80',
    ladder_pref TEXT NOT NULL DEFAULT '4v4_variant',   -- '4v4_variant', '2v2_snd', '1v1_radar', 'all'
    primary_role TEXT DEFAULT 'Flex',                  -- 'Main AR', 'SMG Slayer', 'Entry Sub', 'Flex', 'Sniper / Search'
    secondary_role TEXT DEFAULT 'Main AR',
    elo INT DEFAULT 1200,                              -- ELO / Ladder Rating
    kdr NUMERIC(4,2) DEFAULT 1.15,                     -- Kill / Death Ratio
    platform TEXT DEFAULT 'Crossplay',                 -- 'PC', 'PlayStation 5', 'Xbox Series X', 'Crossplay'
    region TEXT DEFAULT 'NA East',                     -- 'NA East', 'NA Central', 'NA West', 'Europe'
    discord TEXT,                                      -- Discord tag (e.g. tag#0001)
    activision_id TEXT,                                -- Activision ID (e.g. Gamertag#1234567)
    availability TEXT DEFAULT 'Active / Daily',        -- Play schedule
    bio TEXT DEFAULT 'Competitive operator looking for team.',
    mic BOOLEAN DEFAULT TRUE,
    is_active BOOLEAN DEFAULT TRUE,
    is_new_user BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_arena_fa_ladder_pref ON arena_free_agents(ladder_pref);
CREATE INDEX IF NOT EXISTS idx_arena_fa_elo ON arena_free_agents(elo DESC);
CREATE INDEX IF NOT EXISTS idx_arena_fa_active ON arena_free_agents(is_active);

-- ==============================================================================
-- 6. ENABLE ROW LEVEL SECURITY (RLS) & PUBLIC ACCESS POLICIES
-- ==============================================================================
ALTER TABLE ladder_teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE ladder_rosters ENABLE ROW LEVEL SECURITY;
ALTER TABLE ladder_matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE ladder_disputes ENABLE ROW LEVEL SECURITY;
ALTER TABLE arena_free_agents ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    -- ladder_teams policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ladder_teams' AND policyname = 'Allow public select on ladder_teams') THEN
        CREATE POLICY "Allow public select on ladder_teams" ON ladder_teams FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ladder_teams' AND policyname = 'Allow public insert on ladder_teams') THEN
        CREATE POLICY "Allow public insert on ladder_teams" ON ladder_teams FOR INSERT WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ladder_teams' AND policyname = 'Allow public update on ladder_teams') THEN
        CREATE POLICY "Allow public update on ladder_teams" ON ladder_teams FOR UPDATE USING (true);
    END IF;

    -- ladder_rosters policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ladder_rosters' AND policyname = 'Allow public select on ladder_rosters') THEN
        CREATE POLICY "Allow public select on ladder_rosters" ON ladder_rosters FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ladder_rosters' AND policyname = 'Allow public insert on ladder_rosters') THEN
        CREATE POLICY "Allow public insert on ladder_rosters" ON ladder_rosters FOR INSERT WITH CHECK (true);
    END IF;

    -- ladder_matches policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ladder_matches' AND policyname = 'Allow public select on ladder_matches') THEN
        CREATE POLICY "Allow public select on ladder_matches" ON ladder_matches FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ladder_matches' AND policyname = 'Allow public insert on ladder_matches') THEN
        CREATE POLICY "Allow public insert on ladder_matches" ON ladder_matches FOR INSERT WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ladder_matches' AND policyname = 'Allow public update on ladder_matches') THEN
        CREATE POLICY "Allow public update on ladder_matches" ON ladder_matches FOR UPDATE USING (true);
    END IF;

    -- ladder_disputes policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ladder_disputes' AND policyname = 'Allow public select on ladder_disputes') THEN
        CREATE POLICY "Allow public select on ladder_disputes" ON ladder_disputes FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ladder_disputes' AND policyname = 'Allow public insert on ladder_disputes') THEN
        CREATE POLICY "Allow public insert on ladder_disputes" ON ladder_disputes FOR INSERT WITH CHECK (true);
    END IF;

    -- arena_free_agents policies
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'arena_free_agents' AND policyname = 'Allow public select on arena_free_agents') THEN
        CREATE POLICY "Allow public select on arena_free_agents" ON arena_free_agents FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'arena_free_agents' AND policyname = 'Allow public insert on arena_free_agents') THEN
        CREATE POLICY "Allow public insert on arena_free_agents" ON arena_free_agents FOR INSERT WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'arena_free_agents' AND policyname = 'Allow public update on arena_free_agents') THEN
        CREATE POLICY "Allow public update on arena_free_agents" ON arena_free_agents FOR UPDATE USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'arena_free_agents' AND policyname = 'Allow public delete on arena_free_agents') THEN
        CREATE POLICY "Allow public delete on arena_free_agents" ON arena_free_agents FOR DELETE USING (true);
    END IF;
END $$;

-- ==============================================================================
-- 6. SEED INITIAL LADDER SQUADS (Clean initialization - No placeholder teams)
-- ==============================================================================
-- Squads, challenges, and free agents are registered dynamically by users.


