-- ==============================================================================
-- FRONTLINE CALL OF DUTY LEAGUE - COMPLETE MASTER RAILWAY DATABASE SETUP
-- ==============================================================================
-- Clean, standalone PostgreSQL script (No BEGIN/COMMIT, No Extensions required).
-- Drops any partially created tables first to ensure all columns exist cleanly.
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 0. CLEAN SLATE: DROP OLD PARTIAL TABLES (Ensures all columns exist cleanly)
-- ------------------------------------------------------------------------------
DROP TABLE IF EXISTS public.player_map_stats CASCADE;
DROP TABLE IF EXISTS public.team_map_records CASCADE;
DROP TABLE IF EXISTS public.tournament_matches CASCADE;
DROP TABLE IF EXISTS public.tournament_divisions CASCADE;
DROP TABLE IF EXISTS public.scheduled_matches CASCADE;
DROP TABLE IF EXISTS public.ladder_disputes CASCADE;
DROP TABLE IF EXISTS public.ladder_matches CASCADE;
DROP TABLE IF EXISTS public.ladder_rosters CASCADE;
DROP TABLE IF EXISTS public.ladder_teams CASCADE;
DROP TABLE IF EXISTS public.arena_free_agents CASCADE;
DROP TABLE IF EXISTS public.league_signups CASCADE;
DROP TABLE IF EXISTS public.org_signups CASCADE;
DROP TABLE IF EXISTS public.staff_roles CASCADE;
DROP TABLE IF EXISTS public.league_announcements CASCADE;
DROP TABLE IF EXISTS public.league_settings CASCADE;
DROP TABLE IF EXISTS public.vods CASCADE;
DROP TABLE IF EXISTS public.players CASCADE;
DROP TABLE IF EXISTS public.teams CASCADE;

-- ------------------------------------------------------------------------------
-- 1. AUTH COMPATIBILITY & PRIVATE SCHEMAS
-- ------------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS auth;

CREATE TABLE IF NOT EXISTS auth.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT UNIQUE,
    raw_user_meta_data JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE SCHEMA IF NOT EXISTS fcl_private;

-- ------------------------------------------------------------------------------
-- 2. LEAGUE TEAMS TABLE
-- ------------------------------------------------------------------------------
CREATE TABLE public.teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    tag TEXT NOT NULL,
    wins INT DEFAULT 0,
    losses INT DEFAULT 0,
    points INT DEFAULT 0,
    logo_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------------
-- 3. LEAGUE PLAYERS TABLE
-- ------------------------------------------------------------------------------
CREATE TABLE public.players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT REFERENCES public.teams(id) ON DELETE SET NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    gamertag TEXT NOT NULL UNIQUE,
    real_name TEXT,
    role TEXT DEFAULT 'Flex',
    kdr NUMERIC(4, 2) DEFAULT 1.00,
    total_kills INT DEFAULT 0,
    total_deaths INT DEFAULT 0,
    wins INT DEFAULT 0,
    losses INT DEFAULT 0,
    activision_id TEXT,
    discord_name TEXT,
    region TEXT DEFAULT 'NA East',
    platform TEXT DEFAULT 'PC',
    avatar_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_players_user_id ON public.players(user_id);
CREATE INDEX idx_players_gamertag_lower ON public.players(LOWER(gamertag));
CREATE INDEX idx_players_team_id ON public.players(team_id);

-- ------------------------------------------------------------------------------
-- 4. VODS & LIVESTREAMS TABLE
-- ------------------------------------------------------------------------------
CREATE TABLE public.vods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    stage TEXT DEFAULT 'Regular Season',
    match_date DATE DEFAULT CURRENT_DATE,
    team1_id BIGINT REFERENCES public.teams(id) ON DELETE SET NULL,
    team2_id BIGINT REFERENCES public.teams(id) ON DELETE SET NULL,
    team1_score INT DEFAULT 0,
    team2_score INT DEFAULT 0,
    vod_url TEXT NOT NULL,
    is_live BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------------
-- 5. INDIVIDUAL PLAYER MAP STATS TABLE
-- ------------------------------------------------------------------------------
CREATE TABLE public.player_map_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT REFERENCES public.players(id) ON DELETE CASCADE,
    map_name TEXT NOT NULL,
    game_mode TEXT NOT NULL,
    opponent_team TEXT,
    kills INT DEFAULT 0,
    deaths INT DEFAULT 0,
    damage INT DEFAULT 0,
    kdr NUMERIC(4, 2) DEFAULT 1.00,
    result TEXT DEFAULT 'W',
    score TEXT,
    match_date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_player_map_stats_player ON public.player_map_stats(player_id);

-- ------------------------------------------------------------------------------
-- 6. TEAM MAP RECORDS TABLE
-- ------------------------------------------------------------------------------
CREATE TABLE public.team_map_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT REFERENCES public.teams(id) ON DELETE CASCADE,
    map_name TEXT NOT NULL,
    game_mode TEXT NOT NULL,
    wins INT DEFAULT 0,
    losses INT DEFAULT 0,
    win_rate INT DEFAULT 0,
    streak TEXT DEFAULT '1W',
    recent_score TEXT,
    recent_result TEXT DEFAULT 'W',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_team_map_records_team ON public.team_map_records(team_id);

-- ------------------------------------------------------------------------------
-- 7. LEAGUE SIGNUPS / FREE AGENT QUEUE
-- ------------------------------------------------------------------------------
CREATE TABLE public.league_signups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    gamertag TEXT NOT NULL,
    activision_id TEXT,
    discord_username TEXT NOT NULL,
    discord_user_id TEXT,
    role TEXT DEFAULT 'Flex',
    platform TEXT DEFAULT 'PC',
    region TEXT DEFAULT 'NA East',
    registration_type TEXT DEFAULT 'Free Agent',
    team_name TEXT,
    notes TEXT,
    status TEXT DEFAULT 'Pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_league_signups_user_id ON public.league_signups(user_id);
CREATE INDEX idx_league_signups_gamertag ON public.league_signups(gamertag);
CREATE INDEX idx_league_signups_discord_id ON public.league_signups(discord_user_id);

-- ------------------------------------------------------------------------------
-- 8. TEAM / ORG SIGNUPS (WITH PAYMENT TRACKING)
-- ------------------------------------------------------------------------------
CREATE TABLE public.org_signups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_name TEXT NOT NULL,
    team_tag VARCHAR(6) NOT NULL,
    owner_gamertag TEXT NOT NULL,
    owner_discord TEXT NOT NULL,
    contact_email TEXT NOT NULL,
    region TEXT DEFAULT 'NA East',
    logo_url TEXT,
    twitter_handle TEXT,
    player_1_gamertag TEXT NOT NULL,
    player_1_activision TEXT,
    player_1_role TEXT DEFAULT 'SMG',
    player_2_gamertag TEXT NOT NULL,
    player_2_activision TEXT,
    player_2_role TEXT DEFAULT 'Main AR',
    player_3_gamertag TEXT NOT NULL,
    player_3_activision TEXT,
    player_3_role TEXT DEFAULT 'Flex',
    player_4_gamertag TEXT NOT NULL,
    player_4_activision TEXT,
    player_4_role TEXT DEFAULT 'SMG',
    substitute_gamertag TEXT,
    substitute_activision TEXT,
    entry_fee_amount NUMERIC(6,2) DEFAULT 25.00,
    payment_method TEXT DEFAULT 'PayPal',
    status TEXT DEFAULT 'Pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------------
-- 9. LEAGUE ANNOUNCEMENTS
-- ------------------------------------------------------------------------------
CREATE TABLE public.league_announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    tag TEXT DEFAULT 'Official Update',
    tag_color TEXT DEFAULT 'lime',
    image_url TEXT,
    image_fit TEXT DEFAULT 'contain',
    link_url TEXT,
    link_text TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    pinned BOOLEAN DEFAULT FALSE,
    scheduled_for TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------------
-- 10. LEAGUE SEASON SETTINGS
-- ------------------------------------------------------------------------------
CREATE TABLE public.league_settings (
    id TEXT PRIMARY KEY,
    season_number INT DEFAULT 1,
    status_state TEXT DEFAULT 'active',
    status_text TEXT DEFAULT 'SEASON 1 ACTIVE',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------------
-- 11. SCHEDULED MATCHES (8-WEEK MATCH SCHEDULE)
-- ------------------------------------------------------------------------------
CREATE TABLE public.scheduled_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_number INT NOT NULL,
    season_type TEXT NOT NULL DEFAULT 'regular',
    week_label TEXT NOT NULL,
    match_number INT DEFAULT 1,
    team1_id BIGINT REFERENCES public.teams(id) ON DELETE SET NULL,
    team1_name TEXT NOT NULL,
    team1_tag TEXT NOT NULL,
    team1_score INT DEFAULT 0,
    team2_id BIGINT REFERENCES public.teams(id) ON DELETE SET NULL,
    team2_name TEXT NOT NULL,
    team2_tag TEXT NOT NULL,
    team2_score INT DEFAULT 0,
    winner_id BIGINT REFERENCES public.teams(id) ON DELETE SET NULL,
    winner_name TEXT,
    status TEXT DEFAULT 'Scheduled',
    scheduled_date DATE DEFAULT CURRENT_DATE,
    scheduled_time TEXT DEFAULT '7:00 PM EST',
    best_of INT DEFAULT 5,
    stream_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_scheduled_matches_week ON public.scheduled_matches(week_number);
CREATE INDEX idx_scheduled_matches_season ON public.scheduled_matches(season_type);

-- ------------------------------------------------------------------------------
-- 12. TOURNAMENT DIVISIONS
-- ------------------------------------------------------------------------------
CREATE TABLE public.tournament_divisions (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    tier TEXT DEFAULT 'Division 1',
    format TEXT DEFAULT 'Double Elimination (Bo5)',
    prize_pool TEXT DEFAULT '$1,000 USD',
    season TEXT DEFAULT 'Season 1',
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------------
-- 13. TOURNAMENT MATCHES & BRACKETS
-- ------------------------------------------------------------------------------
CREATE TABLE public.tournament_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    division_id TEXT REFERENCES public.tournament_divisions(id) ON DELETE CASCADE,
    match_code TEXT NOT NULL,
    round_name TEXT NOT NULL,
    stage TEXT NOT NULL,
    round_order INT DEFAULT 1,
    match_order INT DEFAULT 1,
    team1_name TEXT NOT NULL,
    team1_tag TEXT NOT NULL,
    team1_seed INT,
    team1_score INT DEFAULT 0,
    team2_name TEXT NOT NULL,
    team2_tag TEXT NOT NULL,
    team2_seed INT,
    team2_score INT DEFAULT 0,
    winner_name TEXT,
    status TEXT DEFAULT 'Scheduled',
    scheduled_time TEXT,
    best_of INT DEFAULT 5,
    mvp_gamertag TEXT,
    mvp_stats TEXT,
    vod_url TEXT,
    maps_data JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_tournament_matches_division ON public.tournament_matches(division_id);

-- ------------------------------------------------------------------------------
-- 13b. TOURNAMENTS (OFFICIAL COMMISSIONER EVENTS & CASH CUPS)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.tournaments (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    format TEXT DEFAULT '4v4 CDL Variant',
    bracket_type TEXT DEFAULT 'Double Elimination',
    prize_pool TEXT DEFAULT '$500 USD',
    entry_fee TEXT DEFAULT 'FREE ENTRY',
    max_teams INT DEFAULT 16,
    registered_teams INT DEFAULT 0,
    start_date TEXT,
    start_time TEXT,
    status TEXT DEFAULT 'Registration Open',
    image_url TEXT,
    registration_url TEXT,
    bracket_url TEXT,
    description TEXT,
    rules_notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------------
-- 13c. TOURNAMENT REGISTRATIONS (LOGGED SQUAD ENTRIES & ROSTERS)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.tournament_registrations (
    id TEXT PRIMARY KEY,
    tournament_id TEXT NOT NULL,
    tournament_title TEXT,
    team_name TEXT NOT NULL,
    captain_gamertag TEXT NOT NULL,
    captain_discord TEXT NOT NULL,
    captain_activision_id TEXT,
    roster JSONB DEFAULT '[]'::jsonb,
    roster_text TEXT,
    status TEXT DEFAULT 'registered',
    registered_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tournament_registrations_tid ON public.tournament_registrations(tournament_id);
CREATE INDEX IF NOT EXISTS idx_tournament_registrations_captain ON public.tournament_registrations(captain_gamertag);

-- ------------------------------------------------------------------------------
-- 14. ARENA FREE AGENTS (LFT LADDER MARKETPLACE)
-- ------------------------------------------------------------------------------
CREATE TABLE public.arena_free_agents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT,
    gamertag TEXT NOT NULL UNIQUE,
    clan_tag VARCHAR(6) DEFAULT 'LFT',
    avatar_url TEXT DEFAULT 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=150&auto=format&fit=crop&q=80',
    ladder_pref TEXT NOT NULL DEFAULT '4v4_variant',
    primary_role TEXT DEFAULT 'Flex',
    secondary_role TEXT DEFAULT 'Main AR',
    elo INT DEFAULT 1200,
    kdr NUMERIC(4,2) DEFAULT 1.00,
    platform TEXT DEFAULT 'PC',
    region TEXT DEFAULT 'NA East',
    discord TEXT,
    activision_id TEXT,
    availability TEXT DEFAULT 'Active / Daily',
    bio TEXT DEFAULT 'Competitive operator looking for team.',
    mic BOOLEAN DEFAULT TRUE,
    is_active BOOLEAN DEFAULT TRUE,
    is_new_user BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------------
-- 15. LADDER ARENA TEAMS (ELO SYSTEM)
-- ------------------------------------------------------------------------------
CREATE TABLE public.ladder_teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    tag VARCHAR(6) NOT NULL,
    avatar_url TEXT,
    ladder_type TEXT NOT NULL DEFAULT '4v4_variant',
    captain_name TEXT NOT NULL,
    captain_discord TEXT,
    elo INT DEFAULT 1200,
    tier TEXT DEFAULT 'Operator',
    wins INT DEFAULT 0,
    losses INT DEFAULT 0,
    streak INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------------
-- 16. LADDER ROSTERS
-- ------------------------------------------------------------------------------
CREATE TABLE public.ladder_rosters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT REFERENCES public.ladder_teams(id) ON DELETE CASCADE,
    gamertag TEXT NOT NULL,
    discord_username TEXT,
    role TEXT DEFAULT 'member',
    joined_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------------
-- 17. LADDER MATCHES
-- ------------------------------------------------------------------------------
CREATE TABLE public.ladder_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ladder_type TEXT NOT NULL DEFAULT '4v4_variant',
    team_a_id BIGINT REFERENCES public.ladder_teams(id) ON DELETE CASCADE,
    team_b_id BIGINT REFERENCES public.ladder_teams(id) ON DELETE SET NULL,
    team_a_score INT DEFAULT 0,
    team_b_score INT DEFAULT 0,
    best_of INT DEFAULT 5,
    status TEXT DEFAULT 'open',
    scheduled_time TIMESTAMPTZ DEFAULT NOW(),
    winner_id BIGINT REFERENCES public.ladder_teams(id) ON DELETE SET NULL,
    reported_by TEXT,
    proof_url TEXT,
    notes TEXT,
    maps_played JSONB,
    elo_change INT DEFAULT 25,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ
);

-- ------------------------------------------------------------------------------
-- 18. LADDER DISPUTES
-- ------------------------------------------------------------------------------
CREATE TABLE public.ladder_disputes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT REFERENCES public.ladder_matches(id) ON DELETE CASCADE,
    disputing_team_id BIGINT REFERENCES public.ladder_teams(id) ON DELETE CASCADE,
    reason TEXT NOT NULL,
    proof_url TEXT,
    status TEXT DEFAULT 'pending',
    resolved_by TEXT,
    resolution_notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    resolved_at TIMESTAMPTZ
);

-- ------------------------------------------------------------------------------
-- 19. STAFF ROLES (RBAC FOR ADMIN PORTAL)
-- ------------------------------------------------------------------------------
CREATE TABLE public.staff_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL UNIQUE,
    display_name TEXT,
    role TEXT NOT NULL DEFAULT 'referee',
    custom_permissions TEXT[],
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_staff_roles_email ON public.staff_roles(email);

-- ------------------------------------------------------------------------------
-- 20. DISCORD ROSTER BOT CONFIG & AUDIT LOGS
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fcl_private.roster_bot_config (
    singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
    guild_id TEXT NOT NULL,
    secret_hash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS fcl_private.roster_audit (
    operation_id UUID PRIMARY KEY,
    guild_id TEXT NOT NULL,
    actor_id TEXT NOT NULL,
    target_id TEXT NOT NULL,
    discord_name TEXT NOT NULL,
    action TEXT NOT NULL,
    team_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    previous_team_id BIGINT,
    result_team_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ------------------------------------------------------------------------------
-- 21. INITIAL DEFAULT DATA (DIVISIONS, SETTINGS, ROLES)
-- ------------------------------------------------------------------------------

-- Default Tournament Divisions
INSERT INTO public.tournament_divisions (id, name, tier, format, prize_pool, season, description)
VALUES 
    ('premier', 'Premier Championship', 'Division 1', 'Double Elimination (Bo5)', '$1,000 USD', 'Season 1', 'Top tier 8-team double elimination bracket.'),
    ('challengers', 'Challengers Cup', 'Division 2', 'Single Elimination (Bo5)', '$500 USD', 'Season 1', 'Mid-tier competitive tournament.'),
    ('open', 'Open Series', 'Division 3', 'Single Elimination (Bo3)', '$250 USD', 'Season 1', 'Open signup grassroots tournament.')
ON CONFLICT (id) DO NOTHING;

-- Default Season Settings
INSERT INTO public.league_settings (id, season_number, status_state, status_text)
VALUES ('season', 1, 'active', 'SEASON 1 ACTIVE')
ON CONFLICT (id) DO UPDATE SET
    season_number = EXCLUDED.season_number,
    status_state = EXCLUDED.status_state,
    status_text = EXCLUDED.status_text;

-- Default Staff Roles
INSERT INTO public.staff_roles (email, display_name, role, notes)
VALUES 
    ('admin@frontlineleague.com', 'League Director', 'commissioner', 'Primary commissioner'),
    ('referee@frontlineleague.com', 'Head Referee', 'referee', 'Match scoring & map stats'),
    ('roster@frontlineleague.com', 'Roster GM', 'roster_manager', 'Squad rosters & enlistment'),
    ('recruiter@frontlineleague.com', 'Recruitment Lead', 'recruiter', 'Signup queue & free agents'),
    ('broadcast@frontlineleague.com', 'Media Crew', 'broadcaster', 'Livestreams & announcements')
ON CONFLICT (email) DO NOTHING;
