-- ==============================================================================
-- FRONTLINE CALL OF DUTY LEAGUE - DISCORD AUTH & REGISTRATION QUEUE AUTOMATION
-- Run this in your Supabase Dashboard -> SQL Editor -> Run
-- ==============================================================================

-- 1. Ensure league_signups table exists and has user_id and discord_user_id columns
CREATE TABLE IF NOT EXISTS public.league_signups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    gamertag TEXT NOT NULL,
    activision_id TEXT,
    discord_username TEXT NOT NULL,
    discord_user_id TEXT,
    role TEXT DEFAULT 'Flex',
    platform TEXT DEFAULT 'PC',
    registration_type TEXT DEFAULT 'Free Agent',
    team_name TEXT,
    region TEXT DEFAULT 'NA East',
    notes TEXT,
    status TEXT DEFAULT 'Pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Safely add columns if the table already existed without them
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' AND table_name = 'league_signups' AND column_name = 'user_id'
    ) THEN
        ALTER TABLE public.league_signups ADD COLUMN user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' AND table_name = 'league_signups' AND column_name = 'discord_user_id'
    ) THEN
        ALTER TABLE public.league_signups ADD COLUMN discord_user_id TEXT;
    END IF;
END $$;

-- 2. Create high-performance indexes for lightning-fast user lookups
CREATE INDEX IF NOT EXISTS idx_league_signups_user_id ON public.league_signups(user_id);
CREATE INDEX IF NOT EXISTS idx_league_signups_discord_user_id ON public.league_signups(discord_user_id);

-- 3. Automatic Trigger Function: Runs every time a user signs up with Discord or Email
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
    d_tag TEXT;
    d_id TEXT;
    d_avatar TEXT;
    d_activision TEXT;
BEGIN
    -- Extract Discord metadata safely from Supabase Auth raw_user_meta_data
    d_tag := COALESCE(
        new.raw_user_meta_data->>'custom_claims'->>'global_name',
        new.raw_user_meta_data->>'full_name',
        new.raw_user_meta_data->>'name',
        new.raw_user_meta_data->>'gamertag',
        new.raw_user_meta_data->>'user_name',
        split_part(new.email, '@', 1),
        'Operative'
    );
    
    d_id := COALESCE(
        new.raw_user_meta_data->>'provider_id',
        new.raw_user_meta_data->>'sub',
        new.raw_user_meta_data->>'discord_user_id'
    );

    d_activision := COALESCE(
        new.raw_user_meta_data->>'activision_id',
        NULL
    );

    -- Insert new entry into the recruitment queue linked to auth user
    INSERT INTO public.league_signups (
        user_id,
        gamertag,
        discord_username,
        discord_user_id,
        activision_id,
        role,
        platform,
        registration_type,
        region,
        notes,
        status,
        created_at
    )
    VALUES (
        new.id,
        d_tag,
        d_tag,
        d_id,
        d_activision,
        'Flex',
        'PC',
        'Free Agent',
        'NA East',
        '[Auto-Synced from Discord/Auth Sign In]',
        'Pending',
        NOW()
    )
    ON CONFLICT DO NOTHING;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. Attach trigger to auth.users table
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 5. Row-Level Security (RLS) Configuration
ALTER TABLE public.league_signups ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    -- Allow public read of signups (e.g. for free agents directory & admin lists)
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'league_signups' AND policyname = 'Allow public select on league_signups'
    ) THEN
        CREATE POLICY "Allow public select on league_signups" ON public.league_signups
            FOR SELECT USING (true);
    END IF;

    -- Allow authenticated users to insert their own signup record
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'league_signups' AND policyname = 'Allow authenticated users insert own signup'
    ) THEN
        CREATE POLICY "Allow authenticated users insert own signup" ON public.league_signups
            FOR INSERT WITH CHECK (auth.uid() = user_id OR user_id IS NULL);
    END IF;

    -- Allow authenticated users to update their own signup record
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'league_signups' AND policyname = 'Allow authenticated users update own signup'
    ) THEN
        CREATE POLICY "Allow authenticated users update own signup" ON public.league_signups
            FOR UPDATE USING (auth.uid() = user_id OR auth.uid() IS NOT NULL) WITH CHECK (true);
    END IF;

    -- Allow staff/admin full access
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'league_signups' AND policyname = 'Allow all access to league_signups'
    ) THEN
        CREATE POLICY "Allow all access to league_signups" ON public.league_signups
            FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;
