-- ==============================================================================
-- FRONTLINE CALL OF DUTY LEAGUE - STAFF ROLES & ROLE-BASED ACCESS CONTROL (RBAC)
-- Run this in your Supabase Dashboard -> SQL Editor (New Query -> Run)
-- ==============================================================================

-- 1. Create staff_roles table
CREATE TABLE IF NOT EXISTS staff_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL UNIQUE,
    display_name TEXT,
    role TEXT NOT NULL DEFAULT 'referee', -- 'commissioner', 'referee', 'stats_official', 'roster_manager', 'recruiter', 'broadcaster', 'rulebook_admin'
    custom_permissions TEXT[], -- optional array of tab IDs e.g. ARRAY['tab-matches', 'tab-schedule']
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create index for high-speed email lookups during login
CREATE INDEX IF NOT EXISTS idx_staff_roles_email ON staff_roles(email);

-- 3. Enable Row-Level Security
ALTER TABLE staff_roles ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies
DO $$
BEGIN
    -- Allow read access for authenticated sessions & client lookups
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'staff_roles' AND policyname = 'Allow read on staff_roles'
    ) THEN
        CREATE POLICY "Allow read on staff_roles" ON staff_roles
            FOR SELECT USING (true);
    END IF;

    -- Allow staff management mutations
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'staff_roles' AND policyname = 'Allow full management on staff_roles'
    ) THEN
        CREATE POLICY "Allow full management on staff_roles" ON staff_roles
            FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;

-- 5. Seed Initial Staff Directory (Optional starter templates)
-- Replace the email addresses with your staff's actual emails:
INSERT INTO staff_roles (email, display_name, role, notes)
VALUES 
    ('admin@frontlineleague.com', 'League Commissioner', 'commissioner', 'Primary league director with full access to all modules')
ON CONFLICT (email) DO UPDATE 
SET role = EXCLUDED.role, display_name = EXCLUDED.display_name, updated_at = NOW();

