-- ==============================================================================
-- FRONTLINE CALL OF DUTY LEAGUE - SUPABASE DATABASE SCHEMA & SEED DATA
-- Copy and paste this entire script into your Supabase Dashboard -> SQL Editor -> Run
-- ==============================================================================

-- 1. DROP EXISTING TABLES IF RE-RUNNING (Clean slate)
DROP TABLE IF EXISTS player_map_stats CASCADE;
DROP TABLE IF EXISTS vods CASCADE;
DROP TABLE IF EXISTS players CASCADE;
DROP TABLE IF EXISTS teams CASCADE;

-- 2. CREATE TEAMS TABLE
CREATE TABLE teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    tag TEXT NOT NULL,
    wins INT DEFAULT 0,
    losses INT DEFAULT 0,
    points INT DEFAULT 0,
    logo_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. CREATE PLAYERS TABLE
CREATE TABLE players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT REFERENCES teams(id) ON DELETE SET NULL,
    gamertag TEXT NOT NULL UNIQUE,
    real_name TEXT,
    role TEXT DEFAULT 'Flex', -- e.g. SMG, Main AR, Flex, Sniper
    kdr NUMERIC(4, 2) DEFAULT 1.00,
    total_kills INT DEFAULT 0,
    total_deaths INT DEFAULT 0,
    avatar_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. CREATE VODS / LIVESTREAMS TABLE (TWITCH INTEGRATION)
CREATE TABLE vods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    stage TEXT DEFAULT 'Regular Season', -- e.g. Week 1, Major I, Grand Finals
    match_date DATE DEFAULT CURRENT_DATE,
    team1_id BIGINT REFERENCES teams(id) ON DELETE SET NULL,
    team2_id BIGINT REFERENCES teams(id) ON DELETE SET NULL,
    team1_score INT DEFAULT 0,
    team2_score INT DEFAULT 0,
    vod_url TEXT NOT NULL, -- Twitch channel name (e.g. 'callofduty'), Twitch URL, or Video ID
    is_live BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. CREATE INDIVIDUAL PLAYER MAP STATS TABLE
CREATE TABLE player_map_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT REFERENCES players(id) ON DELETE CASCADE,
    map_name TEXT NOT NULL,       -- e.g. "Sub Base", "Karachi", "Invasion", "Rio", "Highrise", "6 Star", "Terminal"
    game_mode TEXT NOT NULL,      -- e.g. "Hardpoint", "Search & Destroy", "Control"
    opponent_team TEXT,           -- e.g. "Atlanta FaZe", "OpTic Texas", "Boston Breach"
    kills INT DEFAULT 0,
    deaths INT DEFAULT 0,
    damage INT DEFAULT 0,
    kdr NUMERIC(4, 2) DEFAULT 1.00,
    result TEXT DEFAULT 'W',      -- 'W' or 'L'
    score TEXT,                   -- e.g. '250 - 212', '6 - 4', '3 - 2'
    match_date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. ENABLE ROW LEVEL SECURITY (RLS)
ALTER TABLE teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE players ENABLE ROW LEVEL SECURITY;
ALTER TABLE vods ENABLE ROW LEVEL SECURITY;
ALTER TABLE player_map_stats ENABLE ROW LEVEL SECURITY;

-- 7. ALLOW PUBLIC READ ACCESS (Anyone can view standings, rosters, vods, and map stats)
CREATE POLICY "Allow public read access on teams" ON teams
    FOR SELECT USING (true);

CREATE POLICY "Allow public read access on players" ON players
    FOR SELECT USING (true);

CREATE POLICY "Allow public read access on vods" ON vods
    FOR SELECT USING (true);

CREATE POLICY "Allow public read access on player_map_stats" ON player_map_stats
    FOR SELECT USING (true);

-- ==============================================================================
-- 7. SEED DATA (Clean initialization - No placeholder teams or players)
-- ==============================================================================
-- New database installations begin with clean tables. Teams and players are
-- added via user signups, team registrations, and admin management.


-- ==============================================================================
-- 8. LEAGUE SIGNUPS / REGISTRATIONS TABLE
-- ==============================================================================
CREATE TABLE IF NOT EXISTS league_signups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gamertag TEXT NOT NULL,
    activision_id TEXT,
    discord_username TEXT NOT NULL,
    role TEXT DEFAULT 'Flex',                      -- SMG, Main AR, Flex, Sniper
    platform TEXT DEFAULT 'PC',                    -- PC, PlayStation, Xbox
    registration_type TEXT DEFAULT 'Free Agent',   -- 'Free Agent' or 'Team Captain'
    team_name TEXT,                                -- If registering a squad
    region TEXT DEFAULT 'NA East',                 -- NA East, NA Central, NA West, EU, Other
    notes TEXT,                                    -- Additional player notes or experience
    status TEXT DEFAULT 'Pending',                 -- 'Pending', 'Approved', 'Waitlist'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE league_signups ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'league_signups' 
        AND policyname = 'Allow public insert on league_signups'
    ) THEN
        CREATE POLICY "Allow public insert on league_signups" ON league_signups
            FOR INSERT WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'league_signups' 
        AND policyname = 'Allow public read on league_signups'
    ) THEN
        CREATE POLICY "Allow public read on league_signups" ON league_signups
            FOR SELECT USING (true);
    END IF;
END
$$;

